<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Alert: {{ $alert->title }}</title>
    <style>
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
            line-height: 1.6;
            color: #333;
            background-color: #f4f5f7;
            margin: 0;
            padding: 0;
        }
        .container {
            max-width: 600px;
            margin: 40px auto;
            background: #ffffff;
            border-radius: 8px;
            overflow: hidden;
            box-shadow: 0 2px 8px rgba(0,0,0,0.1);
        }
        .header {
            padding: 24px;
            color: #ffffff;
        }
        .header.critical {
            background: linear-gradient(135deg, #dc2626 0%, #b91c1c 100%);
        }
        .header.warning {
            background: linear-gradient(135deg, #f59e0b 0%, #d97706 100%);
        }
        .header.info {
            background: linear-gradient(135deg, #3b82f6 0%, #2563eb 100%);
        }
        .header h1 {
            margin: 0;
            font-size: 22px;
            font-weight: 600;
        }
        .content {
            padding: 24px;
        }
        .content p {
            margin: 0 0 16px 0;
            font-size: 15px;
            color: #4b5563;
        }
        .details {
            background: #f9fafb;
            border-left: 4px solid #3b82f6;
            padding: 16px;
            margin: 20px 0;
            border-radius: 4px;
        }
        .details table {
            width: 100%;
            border-collapse: collapse;
        }
        .details td {
            padding: 8px 12px;
            font-size: 14px;
        }
        .details td:first-child {
            font-weight: 600;
            color: #6b7280;
            width: 120px;
        }
        .details td:last-child {
            color: #111827;
        }
        .severity-badge {
            display: inline-block;
            padding: 4px 12px;
            border-radius: 12px;
            font-size: 13px;
            font-weight: 600;
            text-transform: uppercase;
        }
        .severity-badge.critical {
            background: #fee2e2;
            color: #dc2626;
        }
        .severity-badge.warning {
            background: #fef3c7;
            color: #d97706;
        }
        .severity-badge.info {
            background: #dbeafe;
            color: #2563eb;
        }
        .footer {
            background: #f9fafb;
            padding: 16px 24px;
            text-align: center;
            font-size: 12px;
            color: #9ca3af;
            border-top: 1px solid #e5e7eb;
        }
        .footer a {
            color: #3b82f6;
            text-decoration: none;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header {{ $alert->severity }}">
            <h1>{{ $alert->title }}</h1>
        </div>
        
        <div class="content">
            <p>{{ $alert->message }}</p>
            
            <div class="details">
                <table>
                    <tr>
                        <td>Environment</td>
                        <td><strong>{{ strtoupper(config('app.env', 'production')) }}</strong></td>
                    </tr>
                    <tr>
                        <td>Severity</td>
                        <td>
                            <span class="severity-badge {{ $alert->severity }}">
                                {{ ucfirst($alert->severity) }}
                            </span>
                        </td>
                    </tr>
                    <tr>
                        <td>Device</td>
                        <td>{{ $alert->device->name }}</td>
                    </tr>
                    <tr>
                        <td>IP Address</td>
                        <td>{{ $alert->device->ip_address }}</td>
                    </tr>
                    <tr>
                        <td>Time</td>
                        <td>{{ $alert->created_at->format('Y-m-d H:i:s') }}</td>
                    </tr>
                    <tr>
                        <td>Status</td>
                        <td>{{ ucfirst($alert->status) }}</td>
                    </tr>
                </table>
            </div>
            
            <p style="font-size: 13px; color: #6b7280; margin-top: 24px;">
                This alert was generated by the CCTV Early Warning Monitor system. 
                Please take appropriate action based on the severity level.
            </p>
        </div>
        
        <div class="footer">
            <p>CCTV Early Warning Monitor &copy; {{ date('Y') }}</p>
            <p>To manage your notification preferences, contact your system administrator.</p>
        </div>
    </div>
</body>
</html>
